repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-toml
      - id: check-yaml
      - id: trailing-whitespace
      - id: end-of-file-fixer

  - repo: local
    hooks:
      - id: shfmt
        name: shfmt
        entry: shfmt -w
        language: system
        types: [shell]

      - id: prettier
        name: prettier
        entry: prettier --write
        language: system
        files: \.(json|jsonc|ya?ml)$
