unbind r
bind r source-file ~/.tmux.conf

set -g prefix C-a
set -g base-index 1

# vim-like pane switching
bind -r k select-pane -U
bind -r j select-pane -D
bind -r h select-pane -L
bind -r l select-pane -R

bind -r Left  resize-pane -L 5
bind -r Right resize-pane -R 5
bind -r Up    resize-pane -U 5
bind -r Down  resize-pane -D 5
