enter_accept = true
filter_mode = "host"
keymap_mode = "vim-insert"
prefers_reduced_motion = true
search_mode = "fuzzy"

[sync]
records = true

[ui]
columns = ["duration", "command"]

[ai]
enabled = true
